<a href="https://colab.research.google.com/github/codedog1229/AI_Expirements/blob/main/%E6%95%B0%E6%8D%AE%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#2.1数据操作

In [1]:
import torch

In [2]:
#创建多维数组tensor
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
#查看某个tensor的形状
x.shape

torch.Size([12])

In [7]:
#查看tensor中元素个数
x.numel()

12

In [8]:
#tensor形状改变,元素的总个数不变
X=x.reshape(3,4)
X,X.shape,X.numel

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 torch.Size([3, 4]),
 <function Tensor.numel>)

In [11]:
#创建全为0的tensor,全为1的tensor,全为随机数的tensor
torch.zeros((2,3,4)),torch.ones((2,3,4)),torch.randn((2,3,4))

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 tensor([[[-1.5139, -0.4753,  0.7102, -0.5118],
          [-0.5484, -1.9017,  0.5431,  0.3396],
          [ 2.1866,  1.1978, -0.9381,  0.5506]],
 
         [[-0.7044, -0.3995, -0.0373, -0.1327],
          [ 0.9071,  1.1344, -0.4645,  0.1911],
          [ 0.6175,  0.0187, -0.7123, -0.3907]]]))

In [12]:
#自定义创建tensor
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

#tensor的运算

In [13]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [14]:
#求幂操作
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

#向量的线性代数运算
向量点积和矩阵乘法

In [ ]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
X,Y

In [ ]:
#矩阵的拼接操作
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=0),